spring:
  application:
    name: ms-product
  datasource:
    url: ${URL_DATABASE:jdbc:mysql://localhost:3306/salebd}
    username: root
    password: 60100440
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
